# This defines a C executable target named "sfw"
cc_binary(
    name = "sfw",
    srcs = ["include/sfw_ct.h",
            "include/sfw_pkt.h",
            "include/sfw_port.h",
            "include/sfw_log.h",
            "src/sfw.c",
            "src/sfw_ct.c",
            "src/sfw_pkt.c",
            "src/sfw_port.c",
            "src/sfw_log.c"],
    copts = [
        "-I/usr/local/include",
        "-Iinclude",
        "-include", "rte_config.h",
        "-march=native",
        "-mrtm",
    ],
    linkopts = [
        "-Wl,--as-needed",
        "-L/usr/local/lib/x86_64-linux-gnu",
        "-lrte_node",
        "-lrte_graph",
        "-lrte_pipeline",
        "-lrte_table",
        "-lrte_pdump",
        "-lrte_port",
        "-lrte_fib",
        "-lrte_pdcp",
        "-lrte_ipsec",
        "-lrte_vhost",
        "-lrte_stack",
        "-lrte_security",
        "-lrte_sched",
        "-lrte_reorder",
        "-lrte_rib",
        "-lrte_mldev",
        "-lrte_regexdev",
        "-lrte_rawdev",
        "-lrte_power",
        "-lrte_net_pcap",
        "-lrte_pcapng",
        "-lrte_member",
        "-lrte_lpm",
        "-lrte_latencystats",
        "-lrte_jobstats",
        "-lrte_ip_frag",
        "-lrte_gso",
        "-lrte_gro",
        "-lrte_gpudev",
        "-lrte_dispatcher",
        "-lrte_eventdev",
        "-lrte_efd",
        "-lrte_dmadev",
        "-lrte_distributor",
        "-lrte_cryptodev",
        "-lrte_compressdev",
        "-lrte_cfgfile",
        "-lrte_bpf",
        "-lrte_bitratestats",
        "-lrte_bbdev",
        "-lrte_acl",
        "-lrte_timer",
        "-lrte_hash",
        "-lrte_metrics",
        "-lrte_cmdline",
        "-lrte_pci",
        "-lrte_ethdev",
        "-lrte_meter",
        "-lrte_net",
        "-lrte_mbuf",
        "-lrte_mempool",
        "-lrte_rcu",
        "-lrte_ring",
        "-lrte_eal",
        "-lrte_telemetry",
        "-lrte_argparse",
        "-lrte_kvargs",
        "-lrte_rcu",
        "-lrte_log",
    ],
)

sh_test(
    name = "test_sfw",
    srcs = ["tests/run_tests_bazel.sh"],
    data = [
        ":sfw",
        "tests/conftest.py",
        "tests/test_sfw.py",
    ],
)
