/* File autogenerated by /home/dpdk1/softwares/dpdk/dpdk-stable-24.11.3/buildtools/dpdk-cmdline-gen.py */
#ifndef GENERATED_COMMANDS_H
#define GENERATED_COMMANDS_H
#include <rte_common.h>
#include <cmdline.h>
#include <cmdline_parse_string.h>
#include <cmdline_parse_num.h>
#include <cmdline_parse_ipaddr.h>

/* Auto-generated handling for command "hash dump" */
extern void
cmd_hash_dump_parsed(void *parsed_result, struct cmdline *cl, void *data);

struct cmd_hash_dump_result {
	cmdline_fixed_string_t hash;
	cmdline_fixed_string_t dump;
};

static cmdline_parse_token_string_t cmd_hash_dump_hash_tok =
	TOKEN_STRING_INITIALIZER(struct cmd_hash_dump_result, hash, "hash");
static cmdline_parse_token_string_t cmd_hash_dump_dump_tok =
	TOKEN_STRING_INITIALIZER(struct cmd_hash_dump_result, dump, "dump");

static cmdline_parse_inst_t cmd_hash_dump = {
	.f = cmd_hash_dump_parsed,
	.data = NULL,
	.help_str = "<hash> <dump> print the contents of the CT table",
	.tokens = {
		(void *)&cmd_hash_dump_hash_tok,
		(void *)&cmd_hash_dump_dump_tok,
		NULL,
	}
};

static __rte_used cmdline_parse_ctx_t ctx[] = {
	&cmd_hash_dump,
	NULL
};

#endif /* GENERATED_COMMANDS_H */
